### ISSUE TITLE
Can't use an apostrophe in the summary field for an article

### ISSUE THREAD

**Issue by DaveBitter** [iodigital-com/io-technology#2]
When using an apostrophe in the summary field of an article. The page fails to build.

I tried escaping the character, but that doesn't seem to work. 

Probably something frontmatter related

**Comment by lucienimmink** [comment]
you can if you use double quotes for the string delimiter :)

**Comment by DaveBitter** [comment]
Using ’ instead of ' worked as well. Saw that in Frank's article he did that
