### ISSUE TITLE
Can someone please add some legal links to the footer?

### ISSUE THREAD

**Issue by jeffmaes** [iodigital-com/io-technology#24]
Hi,

Can someone please add the following links to the footer? For legal purpose.

- [Cookies](https://www.iodigital.com/nl/cookie-policy)
- [Privacy](https://www.iodigital.com/nl/privacy-policy)
- [Voorwaarden](https://www.iodigital.com/nl/algemene-voorwaarden)
- [Disclaimer](https://www.iodigital.com/nl/disclaimer)

Can be links to the iodigital.com website - No need to copy the pages to the subsite.
Thx.

**Comment by sanderdejong88** [comment]
@jeffmaes Is this okey? [https://io-technology-git-feat-legal-links-newio.vercel.app/](https://io-technology-git-feat-legal-links-newio.vercel.app/)

**Comment by jeffmaes** [comment]
> @jeffmaes Is this okey? https://io-technology-git-feat-legal-links-newio.vercel.app/

Thanks a lot @sanderdejong88 !
Seems to be perfect on desktop but a bit too wide on mobile which results in a horizontal scroll. I can always have one of the frontenders in Herentals have a look if you want.

**Comment by sanderdejong88** [comment]
> > @jeffmaes Is this okey? https://io-technology-git-feat-legal-links-newio.vercel.app/
> 
> Thanks a lot @sanderdejong88 ! Seems to be perfect on desktop but a bit too wide on mobile which results in a horizontal scroll. I can always have one of the frontenders in Herentals have a look if you want.

Hehe, I tried to fix this too quickly. My bad! Can you check again?
