### ISSUE TITLE
Interactive elements behind header element

### ISSUE THREAD

**Issue by editedredx** [iodigital-com/io-technology#37]
The header element spans over the entire width of the page but is transparent so you can read text under it anyway. Problem is interactive elements like links won't work so it's really confusing.

example: Clicking the link won't work
![image](https://user-images.githubusercontent.com/642298/174571804-042d5772-5c81-409d-9202-069b086f5d0d.png)

**Comment by sanderdejong88** [comment]
@editedredx do you have time to look into it?

**Comment by sanderdejong88** [comment]
Fixed
